version: "3.9"

services:
  trb-client-back:
    container_name: trb-client-back
    build: .
    env_file:
      - .env
    ports:
      - "50051:50051"
networks:
  default:
    name: trust-bank
    external: true